### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'push' of null

### ISSUE THREAD

**Issue by justgage** [jaredly/reason-language-server#272]
I'm not sure how to reproduce this, but it seems to happen all the time for me. Restarting doesn't seem to help much either. I am running the bsb server independent of the VSCode extension for what it's worth (I want npm start to just work for my co-workers, even if they aren't using VSCode).  However I did off the setting of it running bsb in the background.

```
(node:49177) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'push' of null
    at resolve (/Users/justgage/.vscode/extensions/freebroccolo.reasonml-1.0.38/node_modules/ocaml-language-server/bin/server/processes/merlin.js:85:50)
    at new Promise (<anonymous>)
    at Merlin.sync (/Users/justgage/.vscode/extensions/freebroccolo.reasonml-1.0.38/node_modules/ocaml-language-server/bin/server/processes/merlin.js:85:16)
    at Synchronizer.<anonymous> (/Users/justgage/.vscode/extensions/freebroccolo.reasonml-1.0.38/node_modules/ocaml-language-server/bin/server/session/synchronizer.js:52:39)
    at Generator.next (<anonymous>)
    at /Users/justgage/.vscode/extensions/freebroccolo.reasonml-1.0.38/node_modules/ocaml-language-server/bin/server/session/synchronizer.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/justgage/.vscode/extensions/freebroccolo.reasonml-1.0.38/node_modules/ocaml-language-server/bin/server/session/synchronizer.js:3:12)
    at Synchronizer.doFullSync (/Users/justgage/.vscode/extensions/freebroccolo.reasonml-1.0.38/node_modules/ocaml-language-server/bin/server/session/synchronizer.js:49:16)
    at Synchronizer.<anonymous> (/Users/justgage/.vscode/extensions/freebroccolo.reasonml-1.0.38/node_modules/ocaml-language-server/bin/server/session/synchronizer.js:89:24)
(node:49177) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[Error - 5:15:23 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'push' of null
  Code: -32603 
[Error - 5:15:23 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'push' of null
  Code: -32603 
[Error - 5:15:23 AM] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed with message: Cannot read property 'languages' of undefined
  Code: -32603 
[Error - 5:15:23 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'push' of null
  Code: -32603 
```

The `node_modules/.lsp/debug.log` didn't seem to contain much that related to this error from what I could tell, and contained a lot of information about the project I'm working on which is closed-source, so I didn't include it here.

Even if the fix to this would be making it more defensive, or catching the runtime exception I think this could be a big improvement.

**Comment by jchavarri** [comment]
@justgage the logs seem to indicate that the error is coming from the other Reason extension `freebroccolo.reasonml-1.0.38`, https://github.com/reasonml-editor/vscode-reasonml. Not this one.

`reason-language-server` doesn't run much JavaScript, or at all, as far as I can tell.

**Comment by justgage** [comment]
@jchavarri you're right, sorry forgot to close this issue
