### ISSUE TITLE
1.7.8 crashing (OSX 10.13.3)

### ISSUE THREAD

**Issue by boyswan** [jaredly/reason-language-server#434]
```
[Info  - 10:43:56] Connection to server got closed. Server will restart.
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/.../.vscode/extensions/jaredly.reason-vscode-1.7.8/bin.native (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/.../.vscode/extensions/jaredly.reason-vscode-1.7.8/bin.native (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by prometheansacrifice** [comment]
@boyswan Are you macos `10.13`?  This must be because the prebuilts shipped on the vscode store [was built on macos 10.15](https://github.com/jaredly/reason-language-server/blob/master/.github/workflows/release.yml#L29) (@jaredly I could be wrong here)

Compiling the extension from source locally might help you

**Comment by erlandsona** [comment]
Posting here so as not to muddy the issue list waters.

2 coworkers are having issues with reason-language-server vscode plugin 1.7.8 crashing on OSX 10.15.4

Here's the error output...
```
[Error - 11:08:32 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
    at Object.dispose (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-jsonrpc/lib/main.js:825:25)
    at Object.dispose (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-languageclient/lib/client.js:57:35)
    at LanguageClient.handleConnectionClosed (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-languageclient/lib/client.js:1967:42)
    at LanguageClient.handleConnectionClosed (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-languageclient/lib/main.js:126:15)
    at closeHandler (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-languageclient/lib/client.js:1954:18)
    at CallbackList.invoke (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at closeHandler (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-jsonrpc/lib/main.js:221:26)
    at CallbackList.invoke (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at StreamMessageReader.AbstractMessageReader.fireClose (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-jsonrpc/lib/messageReader.js:135:27)
    at Socket.<anonymous> (/Users/AJP/.vscode/extensions/jaredly.reason-vscode-1.7.8/node_modules/vscode-jsonrpc/lib/messageReader.js:188:62)
    at Socket.emit (events.js:208:15)
    at Pipe.<anonymous> (net.js:588:12)
```

Hoping to get some more Troubleshooting ideas cause we're goin' through the [debug settings](https://github.com/jaredly/reason-language-server#debug-settings) and we've tried most of the .
