### ISSUE TITLE
Reason Language Server extremely slow and repeatedly crashing on Windows

### ISSUE THREAD

**Issue by chrispader** [jaredly/reason-language-server#454]
Dear @jaredly,

i was planning on developing ReasonML on a Windows system in the future, but it seems the Reason Language Server in VS Code is much slower on Windows, compared to Linux or macOS.

IntelliSense and Formatting sometimes take up to more than a minute and sometimes the language server is even randomly crashing and executing the "Restart Reason Language Server" command doesn't seem to work. There is always the same error displayed:
```
Command 'Restart Reason Language Server' resulted in an error (Running the contributed command: 'reason-language-server.restart' failed.)
```

On Linux or macOS i don't experience any of these issues.

I would appreciate a fix for this.

Kind Regards

Christoph Pader

**Comment by jisensee** [comment]
Having the same issue on Windows (Version 1809, OS Build 17763.1282), the following appears in the extension host log when trying to restart RLS, not sure if its related:
`[2020-06-23 10:05:16.291] [exthost] [error] Error: Illegal argument: character must be non-negative
    at Object.t.illegalArgument (c:\VSCode-win32-x64-1.46.1\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:784)
    at new e (c:\VSCode-win32-x64-1.46.1\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:436:473)
    at new e (c:\VSCode-win32-x64-1.46.1\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:434:44)
    at asPosition (c:\VSCode-win32-x64-1.46.1\data\extensions\jaredly.reason-vscode-1.7.8\node_modules\vscode-languageclient\lib\protocolConverter.js:52:16)
    at asRange (c:\VSCode-win32-x64-1.46.1\data\extensions\jaredly.reason-vscode-1.7.8\node_modules\vscode-languageclient\lib\protocolConverter.js:58:31)
    at asCodeLens (c:\VSCode-win32-x64-1.46.1\data\extensions\jaredly.reason-vscode-1.7.8\node_modules\vscode-languageclient\lib\protocolConverter.js:361:53)
    at c:\VSCode-win32-x64-1.46.1\data\extensions\jaredly.reason-vscode-1.7.8\node_modules\vscode-languageclient\lib\protocolConverter.js:374:40
    at Array.map (<anonymous>)
    at asCodeLenses (c:\VSCode-win32-x64-1.46.1\data\extensions\jaredly.reason-vscode-1.7.8\node_modules\vscode-languageclient\lib\protocolConverter.js:374:22)`
This was reproduced with a portable VS Code instance right under C:/ with no other extentions installed.
