### ISSUE TITLE
coc-reason extension fails to download reason-language-server

### ISSUE THREAD

**Issue by ianchanning** [jaredly/reason-language-server#472]
I get the following message that never completes: `Downloading reason-language-server for linux...`.

It never manages to download the reason-language-server, I'm not sure why.

I get the following error in `:CocInfo` which I assume is the problem:

```
2020-11-08T23:57:41.612 ERROR (pid:30463) [extensions] - Error on active extension coc-reason: TypeError: (e.adapter || i.adapter) is not a function
    at e.exports (/home/ian/.config/coc/extensions/node_modules/coc-reason/lib/index.js:8:1961)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/ian/.config/coc/extensions/node_modules/coc-reason/lib/index.js:1:25124
    at async Object.h [as activate] (/home/ian/.config/coc/extensions/node_modules/coc-reason/lib/index.js:1:24811) TypeError: (e.adapter || i.adapter) is not a function
    at e.exports (/home/ian/.config/coc/extensions/node_modules/coc-reason/lib/index.js:8:1961)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/ian/.config/coc/extensions/node_modules/coc-reason/lib/index.js:1:25124
    at async Object.h [as activate] (/home/ian/.config/coc/extensions/node_modules/coc-reason/lib/index.js:1:24811)
```

I can work around this by just manually downloading the reason-language-server and putting it into `~/.config/coc/extensions/node_modules/coc-reason/rls/rls-linux/reason-language-server`

**Comment by phenax** [comment]
Facing the same issue
